name: quanlysvjx-manager

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      COMPOSE_PROJECT_NAME: quanlysvjx
      MANAGER_API_HOST: 0.0.0.0
      MANAGER_API_PORT: 3001
      MANAGER_PROJECT_ROOT: ${MANAGER_PROJECT_ROOT:-${PWD}}
      BACKUP_SCHEDULER_ENABLED: true
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    privileged: true
    restart: unless-stopped
    network_mode: host

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    network_mode: host

  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    user: "0:0"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${MANAGER_PROJECT_ROOT:-${PWD}}/apps/jx-services:/srv
      - ${MANAGER_PROJECT_ROOT:-${PWD}}/apps/jx-services/.code-server:/root/.config
      - ${MANAGER_PROJECT_ROOT:-${PWD}}/apps/jx-services/.code-server/fonts/SourceCodePro/sonkt_SourceCodePro-Regular.ttf:/root/.local/share/fonts/sonkt_SourceCodePro-Regular.ttf:ro
    command: ["--auth", "none", "--bind-addr", "0.0.0.0:8080", "--user-data-dir", "/root/.config/data", "--extensions-dir", "/root/.config/extensions", "/srv/active"]
