FROM centos:7

ENV TZ=Asia/Ho_Chi_Minh
## Ensure yum can reach packages for EOL CentOS 7 by using vault.centos.org
RUN for f in /etc/yum.repos.d/*.repo; do \
		sed -i 's/^mirrorlist=/#mirrorlist=/g' "$f"; \
		sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' "$f"; \
	done \
	&& yum -y makecache || true \
	&& yum -y update \
	&& yum -y install libuuid.i686 libcrypto.so.6 libcurl.so.4 \
	&& yum clean all

WORKDIR /src/jxser/server1/

CMD [ "./jx_linux_y" ]